name: Construction et tests API Spring Boot

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Compilation du projet
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Configuration de JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven
        id: cache-maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Compilation (sans tests)
        run: mvn -f legacy-software/pom.xml clean install -DskipTests

    outputs:
      cache-hit: ${{ steps.cache-maven.outputs.cache-hit }}

  test:
    name: Exécution des tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Configuration de JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Exécution des tests
        run: mvn test -f legacy-software/pom.xml
